### ISSUE TITLE
list() and list2() bug

### ISSUE THREAD

**Issue by kenny-nt** [ZackaryW/pyldplayer#1]
ld = LDPlayer()
devices = ld.list2()
print(devices)
Output:

Output don't have the first instance (don't have Instance id = 0)

**Comment by ZackaryW** [comment]
Did notice this issue working on the dev branch,

The easy fix is:
remove these 2 lines in the source files `pyldplayer/player.py` 
at 263-264
![image](https://github.com/ZackaryW/pyldplayer/assets/36378555/584e9521-4d5b-4290-9a12-b50a601cf1ec)

futureproof fix:
dev branch modification
```
parsed = comm.decode("utf-8")
        
# return stripped and splitted
parsed = parsed.strip().split("\r\n")

parsed = list(filter(None, parsed))
parsed = list(map(lambda x: x.strip(), parsed))

return parsed
```
